global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alerts@tradingsystem.com'
  smtp_auth_username: 'alerts@tradingsystem.com'
  smtp_auth_password: '{{ SMTP_PASSWORD }}'
  smtp_require_tls: true
  slack_api_url: '{{ SLACK_API_URL }}'

templates:
  - '/etc/alertmanager/templates/*.tmpl'

route:
  group_by: ['alertname', 'category']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'team-slack'
  routes:
    - match:
        severity: critical
      receiver: 'critical-team'
      continue: true
      group_wait: 0s
      repeat_interval: 30m
    - match:
        category: system
      receiver: 'system-team'
      continue: true
    - match:
        category: component
      receiver: 'system-team'
      continue: true
    - match:
        category: trading
      receiver: 'trading-team'
      continue: true
    - match:
        category: model
      receiver: 'ml-team'
      continue: true
    - match:
        category: data
      receiver: 'data-team'
      continue: true

inhibit_rules:
  # Don't notify about component degraded if the component is down
  - source_match:
      alertname: 'ComponentDown'
    target_match:
      alertname: 'ComponentDegraded'
    equal: ['component']
  
  # Don't notify about individual component issues if circuit breaker is triggered
  - source_match:
      alertname: 'CircuitBreakerTriggered'
    target_match:
      category: 'component'
    equal: []

  # Don't notify about high order rejection if we know high execution latency exists
  - source_match:
      alertname: 'HighExecutionLatency'
    target_match:
      alertname: 'HighOrderRejectionRate'
    equal: []

receivers:
  - name: 'team-slack'
    slack_configs:
      - channel: '#trading-alerts'
        send_resolved: true
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.alertname }}'
        title_link: '{{ template "slack.default.titlelink" . }}'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Severity:* {{ .Labels.severity }}
            *Started:* {{ .StartsAt | since }}
            {{ if .Labels.instance }}*Instance:* {{ .Labels.instance }}{{ end }}
            {{ if .Labels.component }}*Component:* {{ .Labels.component }}{{ end }}
          {{ end }}

  - name: 'critical-team'
    slack_configs:
      - channel: '#critical-alerts'
        send_resolved: true
        title: '🚨 [{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}'
        title_link: '{{ template "slack.default.titlelink" . }}'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Started:* {{ .StartsAt | since }}
            {{ if .Labels.instance }}*Instance:* {{ .Labels.instance }}{{ end }}
            {{ if .Labels.component }}*Component:* {{ .Labels.component }}{{ end }}
          {{ end }}
    pagerduty_configs:
      - service_key: '{{ PAGERDUTY_SERVICE_KEY }}'
        send_resolved: true
        description: '{{ .GroupLabels.alertname }}: {{ .CommonAnnotations.summary }}'
        details:
          description: '{{ .CommonAnnotations.description }}'
          num_firing: '{{ .Alerts.Firing | len }}'
          num_resolved: '{{ .Alerts.Resolved | len }}'

  - name: 'system-team'
    slack_configs:
      - channel: '#system-alerts'
        send_resolved: true
        title: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}'
        title_link: '{{ template "slack.default.titlelink" . }}'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Severity:* {{ .Labels.severity }}
            *Started:* {{ .StartsAt | since }}
            {{ if .Labels.instance }}*Instance:* {{ .Labels.instance }}{{ end }}
            {{ if .Labels.component }}*Component:* {{ .Labels.component }}{{ end }}
          {{ end }}

  - name: 'trading-team'
    slack_configs:
      - channel: '#trading-alerts'
        send_resolved: true
        title: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}'
        title_link: '{{ template "slack.default.titlelink" . }}'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Severity:* {{ .Labels.severity }}
            *Started:* {{ .StartsAt | since }}
            {{ if .Labels.component }}*Component:* {{ .Labels.component }}{{ end }}
          {{ end }}

  - name: 'ml-team'
    slack_configs:
      - channel: '#ml-alerts'
        send_resolved: true
        title: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}'
        title_link: '{{ template "slack.default.titlelink" . }}'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Severity:* {{ .Labels.severity }}
            *Started:* {{ .StartsAt | since }}
            {{ if .Labels.component }}*Component:* {{ .Labels.component }}{{ end }}
          {{ end }}

  - name: 'data-team'
    slack_configs:
      - channel: '#data-alerts'
        send_resolved: true
        title: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}'
        title_link: '{{ template "slack.default.titlelink" . }}'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Severity:* {{ .Labels.severity }}
            *Started:* {{ .StartsAt | since }}
            {{ if .Labels.data_type }}*Data Type:* {{ .Labels.data_type }}{{ end }}
            {{ if .Labels.collector }}*Collector:* {{ .Labels.collector }}{{ end }}
          {{ end }}
