global:
  scrape_interval: 15s # Scrape targets every 15 seconds
  evaluation_interval: 15s # Evaluate rules every 15 seconds
  scrape_timeout: 10s # Timeout for scrape requests

# Using Grafana for alerts - no alertmanager configuration needed

# Rule files to load
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Scrape configurations
scrape_configs:
  # System metrics exporter
  - job_name: 'system_metrics'
    static_configs:
      - targets: ['localhost:8001']
    scrape_interval: 15s

  # Trading metrics exporter
  - job_name: 'trading_metrics'
    static_configs:
      - targets: ['localhost:8002']
    scrape_interval: 5s

  # Model metrics exporter
  - job_name: 'model_metrics'
    static_configs:
      - targets: ['localhost:8003']
    scrape_interval: 30s

  # MLflow Server
  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']
    scrape_interval: 30s

  # PostgreSQL / TimescaleDB Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:9121']
    scrape_interval: 15s

  # Node Exporter (system metrics)
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
